[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Raj Dsouza", email = "raj@webtize.com.au"}]
dynamic = ["version", "description"]
